server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    password: root
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true